# This is a sample configuration file. Defaults are listed,
# only change that are required is what zones to cache.


# Server: This setting is required to be set in the configuration file
# Client: Only need to be set if used without server
# These server/client must be able to do AXFR for the zones.
Zones = [ "zon1.example.tld", "zone2.example.tld" ]

# Server: The port the server tries to bind to
# Client: The port to connect to
# ServerPort = 8080

# Server: Unused
# Client: URL to connect to server
# Defaults to that the server is running on localhost
# ServerURL = "http://localhost"

# Server: Time To Live, how often the server will try to update its cache.
# Client: Unused
# TTL = 900

# Server: Enable opentracing
# Client: Enable opentracing
# Tracing = false

# Server: More verbose information
# Client: More verbose information
# Verbose = false

# Server: Use this server for all AXFR instead of lookup NS for each zone
# Client: Use this server for all AXFR instead of lookup NS for each zone
# NS = ""
